# Generated by Django 5.2.11 on 2026-03-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('identification', models.ImageField(blank=True, null=True, upload_to='doctor_id_proofs/')),
                ('specialization', models.CharField(max_length=50)),
                ('medical_registration_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
