# Generated by Django 5.2.11 on 2026-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0002_tbl_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='specialization',
            field=models.CharField(max_length=30),
        ),
    ]
