# Generated by Django 5.2.11 on 2026-03-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0003_tbl_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
