# Generated by Django 5.2.11 on 2026-03-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0004_tbl_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='password',
            field=models.CharField(blank=True, default='temp123', max_length=128),
            preserve_default=False,
        ),
    ]
