# Generated by Django 5.2.11 on 2026-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0005_alter_tbl_doctor_password'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appointment',
            name='token_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='tbl_appointment',
            options={'ordering': ['appointment_date', 'token_number']},
        ),
        migrations.RemoveConstraint(
            model_name='tbl_appointment',
            name='end_time_after_start_time',
        ),
        migrations.RenameField(
            model_name='tbl_appointment',
            old_name='end_time',
            new_name='estimated_time',
        ),
        migrations.AlterUniqueTogether(
            name='tbl_appointment',
            unique_together={('doctor', 'appointment_date', 'token_number')},
        ),
        migrations.RemoveField(
            model_name='tbl_appointment',
            name='start_time',
        ),
    ]
