# Generated by Django 5.2.11 on 2026-04-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_tbl_patient_first_name'),
        ('patient', '0002_alter_tbl_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('confidence', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='patient_reports/')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='guest.tbl_patient')),
            ],
        ),
    ]
