# Generated by Django 5.2.11 on 2026-04-14 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_report',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.tbl_appointment'),
        ),
    ]
