# Generated by Django 5.2.11 on 2026-04-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_tbl_report_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_report',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
