# Generated by Django 5.2.11 on 2026-02-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_patient',
            name='last_name',
        ),
    ]
