# Generated by Django 5.2.11 on 2026-02-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_remove_tbl_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_patient',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
