# Generated by Django 5.2.11 on 2026-03-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0005_alter_tbl_doctor_password'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorSchedule',
            new_name='tbl_schedule',
        ),
    ]
