# Generated by Django 5.2.11 on 2026-03-11 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_tbl_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_schedule',
            name='schedule_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='tbl_slot',
        ),
    ]
