# Generated by Django 5.2.11 on 2026-03-11 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0005_alter_tbl_doctor_password'),
        ('doctor', '0004_tbl_schedule_schedule_date_delete_tbl_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('slot_start', models.TimeField()),
                ('slot_end', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicadmin.tbl_doctor')),
            ],
        ),
    ]
