# Generated by Django 5.2.11 on 2026-03-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_tbl_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_slot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.tbl_schedule'),
        ),
    ]
