# Generated by Django 5.2.11 on 2026-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_tbl_slot_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_schedule',
            name='total_patients',
            field=models.IntegerField(default=0),
        ),
    ]
