# Generated by Django 5.2.11 on 2026-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_tbl_schedule_slot_duration_tbl_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_schedule',
            name='consultation_duration',
            field=models.IntegerField(default=15),
        ),
    ]
