# Generated by Django 5.2.11 on 2026-03-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_tbl_schedule_consultation_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_token',
        ),
    ]
