# Generated by Django 5.2.11 on 2026-03-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicadmin', '0005_alter_tbl_doctor_password'),
        ('doctor', '0010_delete_tbl_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('token_number', models.IntegerField()),
                ('estimated_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicadmin.tbl_doctor')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.tbl_schedule')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'token_number')},
            },
        ),
    ]
