# Generated by Django 5.2.11 on 2026-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_tbl_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
